name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    # Define os serviços necessários, como bancos de dados.
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: desenvolvimento
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Define opções de inicialização do serviço.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      # Aqui você pode adicionar passos para rodar os testes
      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/desenvolvimento
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
