name: maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  custom-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and Test
        run: |
          javac -cp "src/main/java" "src/test/java/com/yourpackage/*Test.java"
          java -cp "src/main/java:src/test/java" org.junit.runner.JUnitCore com.yourpackage.SimpleTest


