on:
  push:
    branches:
      - main  # Ajuste para corresponder ao nome da sua branch de produção, se necessário.

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests  # Ajuste os parâmetros do Maven conforme necessário.

      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: |
          echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build docker image
        run: docker build -t francismario/banking-api .

      - name: Push image docker
        run: docker push francismario/banking-api

  deploy:
    needs: build_and_push
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: docker pull francismario/banking-api:latest
      - name: Remove docker container
        run: docker rm -f deploy_application_api
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME:${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD:'${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL:${{secrets.DATABASE_URL}} --name deploy_application_api francismario/banking-api
