name: Deploy to Production

on:
  push:
    branches:
      - main  # Ajuste para corresponder ao nome da sua branch de produção, se necessário.

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build project
      run: mvn clean install -DskipTests  # Ajuste os parâmetros do Maven conforme necessário.

    - name: Login Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build docker image
      run: docker build -t francismario/banking-api .

    - name: Push image docker
      run: docker push francismario/banking-api
